### ISSUE TITLE
CP construction error， system can not find specified file

### ISSUE THREAD

**Issue by mz1874** [Ai-Thinker-Open/AiPi-Open-Kits#2]
Once we finish compile（compile is successful） in windows 。  
The shell will run a CP command to copy something， then a error will be occupied that system can not find specified file。
Please help us to fix it

**Comment by SeaHi-Mo** [comment]
If you are not using Ai Eyes R1/R2, you can temporarily comment out the cp instruction。We are thinking of a better way to meet the burning issue of Ai Eyes R1/R2
