### ISSUE TITLE
按照教程编译helloworld的时候，错误提示缺少 lwip/dns.h

### ISSUE THREAD

**Issue by wzh823** [Ai-Thinker-Open/AiPi-Open-Kits#5]
[ 97%] Built target libc
make[1]: *** [Makefile:91: all] Error 2
make: *** [../../project.build:73: build] Error 2
wzh@USER-20230518XF:/mnt/e/project/AiPi-Open-Kits/aithinker_Ai-M6X_SDK/examples/helloworld$ make
./../../tools/cmake/bin/cmake -S . -B build -G "Unix Makefiles" -DCROSS_COMPILE=riscv64-unknown-elf- -DCHIP=bl616 -DCPU_ID= -DBOARD=bl616dk -DBOARD_DIR= -DCONFIG_DEBUG=y -DCONFIG_ROMAPI=y -DCONFIG_USB_HS=y -DCONFIG_COMX=/dev/ttyUSB0 -DCMAKE_EXPORT_COMPILE_COMMANDS=OFF -DCONFIG_TLSF=y
-- [register library : libc], path:/mnt/e/project/AiPi-Open-Kits/aithinker_Ai-M6X_SDK/components/libc
-- [register library : mm], path:/mnt/e/project/AiPi-Open-Kits/aithinker_Ai-M6X_SDK/components/mm
-- [register library : utils], path:/mnt/e/project/AiPi-Open-Kits/aithinker_Ai-M6X_SDK/components/utils
-- [register library : lhal], path:/mnt/e/project/AiPi-Open-Kits/aithinker_Ai-M6X_SDK/drivers/lhal
-- [register extern library : libcsi_xt900p32f_dsp], path:/mnt/e/project/AiPi-Open-Kits/aithinker_Ai-M6X_SDK/drivers/lhal
-- [register extern library : libpka], path:/mnt/e/project/AiPi-Open-Kits/aithinker_Ai-M6X_SDK/drivers/lhal
-- [register library : std], path:/mnt/e/project/AiPi-Open-Kits/aithinker_Ai-M6X_SDK/drivers/soc/bl616/std
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/e/project/AiPi-Open-Kits/aithinker_Ai-M6X_SDK/examples/helloworld/build
make -C build -j8
[  0%] Building C object CMakeFiles/app.dir/mnt/e/project/AiPi-Open-Kits/aithinker_Ai-M6X_SDK/bsp/board/bl616dk/board.c.o
[  3%] Built target mm
[  8%] Built target utils
[ 22%] Built target std
[ 86%] Built target lhal
[ 96%] Built target libc
/mnt/e/project/AiPi-Open-Kits/aithinker_Ai-M6X_SDK/bsp/board/bl616dk/board.c:11:10: fatal error: lwip/dns.h: No such file or directory
   11 | #include "lwip/dns.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/app.dir/build.make:76: CMakeFiles/app.dir/mnt/e/project/AiPi-Open-Kits/aithinker_Ai-M6X_SDK/bsp/board/bl616dk/board.c.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:482: CMakeFiles/app.dir/all] Error 2
make[1]: *** [Makefile:91: all] Error 2
make: *** [../../project.build:73: build] Error 2

**Comment by SeaHi-Mo** [comment]
在新的版本中已经删掉这个部分了，可以正常使用
